import React from 'react';
import { MODULE, SUB_MODULE } from '../constants/subscription';
const USER_PATHS = 'writi-admin|pharmacy|organizations|home|home-area';
const routes = {
  demo: { path: '/demo', id: null, module: null },
  init: { path: '/', id: null, module: null },
  login: { path: '/login', id: null, module: null },
  verifyOtp: { path: '/verify-otp', id: null, module: null },
  pmr: { path: '/pmr', id: 20, module: MODULE.PMR },
  viewResident: { path: '/resident-detail', id: 21, module: MODULE.RESIDENT },
  residentDocument: {
    path: '/resident-documents',
    id: 22,
    module: MODULE.RESIDENT_DOCUMENT,
  },
  residents: { path: '/residents', id: 2, module: MODULE.RESIDENT },
  physicianReview: { path: '/physician-review', id: null, module: MODULE.PMR },
  addPmr: { path: '/add-pmr', id: null, module: MODULE.PMR },
  nursePrep: { path: '/nurse-prep', id: null, module: MODULE.PMR },
  notification: { path: '/notification', id: 73 },
  virtualvisitrequest: {
    path: '/virtualvisitrequest',
    id: 471,
    module: MODULE.VIRTUAL_VISIT,
  },
  chat: { path: '/chat', id: 72 },
  todo: { path: '/todo-detail', id: 10, module: MODULE.TODO },
  pmrTodo: { path: '/pmr-detail', module: MODULE.PMR },
  medReviewTodo: { path: '/pmr-todo', module: MODULE.PMR },
  order: { path: '/wa/orders?type=order', id: 61, module: MODULE.RX_ORDER },
  todoDashboard: { path: '/todo-dashboard', id: null, module: MODULE.TODO },
  pageNotFound: { path: '/pageNotFound', id: null },
  unAuthorizedPage: { path: '/unauthorized-page', id: null },
  forgotPassword: { path: '/forgotPassword', id: null },
  xRayList: { path: '/x-ray-req-list', id: 161, module: MODULE.X_RAY_US },
  xRayRequest: { path: '/x-ray-req', id: 162, module: MODULE.X_RAY_US },
  master: { path: '/master', id: 81, module: MODULE.MASTER },
  submaster: {
    path: '/sub-master/:id',
    id: 81,
    module: MODULE.MASTER,
    mainPath: '/sub-master',
  },
  profile: '/profile',
  permission: '/permission',
  version: '/version-apk',
  subscription: {
    path: '/subscription',
    id: 91,
    module: MODULE.SUBSCRIPTION_GROUP,
  },
  rolePermission: {
    path: '/role-permission',
    id: 92,
    module: MODULE.ROLE_BASE_ACCESS_PERMISSION,
  },
  pharmacy: { path: '/clientele/pharmacy', id: 31, module: MODULE.PHARMACY },
  imagingDiagnostics: {
    path: '/clientele/imaging-diagnostics',
    id: 32,
    module: MODULE['IMAGING_DIAGNOSIS'],
  },
  clientele: {
    path: '/clientele',
    id: 33,
    module: MODULE.ORG_HOME,
    mainPath: '/clientele',
    isCustomer: true,
  },
  pharmacyUpsert: {
    path: '/clientele/pharmacy/upsert',
    id: 36,
    module: MODULE.PHARMACY,
  },
  imagingUpsert: {
    path: '/clientele/imaging-diagnostics/upsert',
    id: 37,
    module: MODULE['IMAGING_DIAGNOSIS'],
  },
  clienteleUpsert: {
    path: '/clientele/upsert',
    id: 38,
    module: MODULE.ORG_HOME,
    isCustomer: true,
  },

  userGeneral: { path: `/user/:userType`, id: 1 },
  userAdmin: { path: `/user/writi-admin`, id: 11, module: MODULE.USER },
  userPharmacy: { path: `/user/pharmacy`, id: 12, module: MODULE.PHARMACY },
  userOrganization: {
    path: `/user/organizations`,
    id: 13,
    module: MODULE.ORG_HOME,
  },
  userHome: {
    path: `/user/home`,
    id: 14,
    module: MODULE.ORG_HOME,
    isHome: true,
  },
  userHomeArea: { path: `/user/home-area`, id: 15 },
  userAdd: { path: `/user-t/upsert`, module: MODULE.USER },
  updateDefaultPassword: { path: '/update-default-password', module: null },
  resetPassword: { path: '/wa/reset-password/:id', module: null },
  pmrGroup: { path: '/pmr-schedule-group', module: MODULE.PMR, subModule: SUB_MODULE.PMR_GROUP },
  pcc: { path: '/point-click-care', module: MODULE.PCC_DATA },
  pccLog: { path: '/pcc-logs', module: MODULE.PCC_DATA },
  feedback: { path: '/feedback', module: MODULE.FEEDBACK },
  supportFeedback: { path: '/support-feedback', module: MODULE.SUPPORT },
};
export default routes;
