export const ADMISSION_READMISSION_TODO_TYPES = {
  "NURSE_PREP_1": 32,
  "BPMH_CHECK": 33,
  "PAR": 34, // Physician Admission Readmission 
  "CONSENT_OBTAINED": 35,
  "E_BOX_USED": 36,
  "DRUG_RECORD": 37,
  "CARE_PLAN": 38,
  "X_RAY_DIET": 39,
  "CHANGE_STICKER": 40,
  "FIRST_CHECK": 41,
  "SECOND_CHECK": 42,
  "VERBAL_ORDER": 43,
  "GENERAL": 44
};

export const AR_PROCESS_TYPE = {
  INITIATED: 1,
  COMPLETED: 2
};
export const ADMISSION_READMISSION_NAME = {
  "NURSE_PREP_1": "NURSE_PREP_1",
  "BPMH_CHECK": "BPMH_CHECK",
  "PAR": "PHYSICIAN_ADMISSION_READMISSION", // Physician Admission Readmission 
  "CONSENT_OBTAINED": "CONSENT",
  "E_BOX_USED": "E_BOX_USED",
  "DRUG_RECORD": "DRUG_RECORD",
  "CARE_PLAN": "CARE_PLAN",
  "X_RAY_DIET": "X_RAY_DIET",
  "CHANGE_STICKER": "CHANGE_STICKER",
  "FIRST_CHECK": "1st_eMAR/eTAR",
  "SECOND_CHECK": "2nd_eMAR/eTAR",
  "VERBAL_ORDER": "VERBAL_ORDER",
  "GENERAL": "GENERAL",
};