import { MODULE } from './subscription'
export const
  TODO_CATEGORY = {
    PRESCRIPTION: MODULE.RX_ORDER,
    PATIENT_INFO: MODULE.RESIDENT,
    MED_REVIEW: MODULE.PMR,
    COMPRESSION_STOCKING: 4,
    ADMISSION_READMISSION: MODULE.ADMISSION_READMISSION,
    RESIDENT_DOCUMENT: MODULE.RESIDENT_DOCUMENT,
    VIRTUAL_VISIT: MODULE.VIRTUAL_VISIT,
    X_RAY: MODULE.X_RAY_US,

  },
  STATUS = {
    SUBMITTED: 1,
    COMPLETED: 2,
    CANCELLED: 3,
    UNDO: 4
  },
  DEVICE_VIEW = {
    "PENDING": 1,
    "HISTORY": 2,
    "OBTAINED_BY_YOU": 3,
    "PRIMARY": 4,
    "SECONDARY": 5
  },
  SUB_CATEGORY = {
    PRESCRIPTION: {
      "CONSENT_OBTAINED": 1,
      "FIRST_CHECK": 2,
      "SECOND_CHECK": 3,
      "VERBAL_ORDER": 4,
      "E_BOX_USED": 14,
      "DRUG_RECORD": 15,
      "CARE_PLAN": 16,
      "X_RAY_DIET": 17,
      "CHANGE_STICKER": 18,
    },
    PATIENT_INFO: {
      "DEMOGRAPHIC_EDIT": 5,
      "REACTIVATION_REQUEST": 6
    },
    MED_REVIEW: {
      "CONSENT_OBTAINED": 22,
      "FIRST_CHECK": 23,
      "SECOND_CHECK": 24,
      "E_BOX_USED": 25,
      "DRUG_RECORD": 26,
      "CARE_PLAN": 27,
      "X_RAY_DIET": 28,
      "CHANGE_STICKER": 29,
      "PMR": 19,
      "NURSE_REVIEW_1": 20,
      "NURSE_REVIEW_2": 21,
      "MEDS_CHECK": 31,
      "PHARMACY_COMMENT": 45
    },
    ADMISSION_READMISSION: {
      "NURSE_PREP_1": 32,
      "BPMH_CHECK": 33,
      "PAR": 34, // Physician Admission Readmission 
      "CONSENT_OBTAINED": 35,
      "E_BOX_USED": 36,
      "DRUG_RECORD": 37,
      "CARE_PLAN": 38,
      "X_RAY_DIET": 39,
      "CHANGE_STICKER": 40,
      "FIRST_CHECK": 41,
      "SECOND_CHECK": 42,
      "VERBAL_ORDER": 43
    },
    XRAY: {
      "XRAY_RESULT": 44
    },
    NOTES: {
      "GENERAL": 50
    }
  }

export const X_RAY_TODO_TYPES = {
  //use constant of subcategory ..remove this while working with xray module
  "GENERAL": 47,
  "X_RAY_RESULT": 44
}

export const TODO_TYPES = {
  CONSENT_OBTAINED: 1,
  FIRST_CHECK: 2,
  SECOND_CHECK: 3,
  VERBAL_ORDER: 4,
  E_BOX_USED: 14,
  DRUG_RECORD: 15,
  CARE_PLAN: 16,
  X_RAY_DIET: 17,
  CHANGE_STICKER: 18
};

export const MAP_TODOS = {
  'CONSENT_OBTAINED': [SUB_CATEGORY.PRESCRIPTION.CONSENT_OBTAINED,
  SUB_CATEGORY.MED_REVIEW.CONSENT_OBTAINED,
  SUB_CATEGORY.ADMISSION_READMISSION.CONSENT_OBTAINED],
  'FIRST_CHECK': [SUB_CATEGORY.PRESCRIPTION.FIRST_CHECK,
  SUB_CATEGORY.MED_REVIEW.FIRST_CHECK,
  SUB_CATEGORY.ADMISSION_READMISSION.FIRST_CHECK],
  'SECOND_CHECK': [SUB_CATEGORY.PRESCRIPTION.SECOND_CHECK,
  SUB_CATEGORY.MED_REVIEW.SECOND_CHECK,
  SUB_CATEGORY.ADMISSION_READMISSION.SECOND_CHECK],
  'VERBAL_ORDER': [SUB_CATEGORY.PRESCRIPTION.VERBAL_ORDER,
  SUB_CATEGORY.MED_REVIEW.VERBAL_ORDER,
  SUB_CATEGORY.ADMISSION_READMISSION.VERBAL_ORDER],
  'E_BOX_USED': [SUB_CATEGORY.PRESCRIPTION.E_BOX_USED,
  SUB_CATEGORY.MED_REVIEW.E_BOX_USED,
  SUB_CATEGORY.ADMISSION_READMISSION.E_BOX_USED],
  'DRUG_RECORD': [SUB_CATEGORY.PRESCRIPTION.DRUG_RECORD,
  SUB_CATEGORY.MED_REVIEW.DRUG_RECORD,
  SUB_CATEGORY.ADMISSION_READMISSION.DRUG_RECORD],
  'CARE_PLAN': [SUB_CATEGORY.PRESCRIPTION.CARE_PLAN,
  SUB_CATEGORY.MED_REVIEW.CARE_PLAN,
  SUB_CATEGORY.ADMISSION_READMISSION.CARE_PLAN],
  'X_RAY_DIET': [SUB_CATEGORY.PRESCRIPTION.X_RAY_DIET,
  SUB_CATEGORY.MED_REVIEW.X_RAY_DIET,
  SUB_CATEGORY.ADMISSION_READMISSION.X_RAY_DIET],
  'CHANGE_STICKER': [SUB_CATEGORY.PRESCRIPTION.CHANGE_STICKER,
  SUB_CATEGORY.MED_REVIEW.CHANGE_STICKER,
  SUB_CATEGORY.ADMISSION_READMISSION.CHANGE_STICKER],
  'NURSE_REVIEW_1': [SUB_CATEGORY.MED_REVIEW.NURSE_REVIEW_1],
  'NURSE_REVIEW_2': [SUB_CATEGORY.MED_REVIEW.NURSE_REVIEW_2],
  'PMR': [SUB_CATEGORY.MED_REVIEW.PMR],
  'MEDS_CHECK': [SUB_CATEGORY.MED_REVIEW.MEDS_CHECK]
}

export const TODO_ICONS = {
  CONSENT_OBTAINED: 'consent.svg',
  FIRST_CHECK: 'first-emar.svg',
  SECOND_CHECK: 'second-emar.svg',
  VERBAL_ORDER: 'verbal-order.svg',
  E_BOX_USED: 'e-box.svg',
  DRUG_RECORD: 'drugs.svg',
  CARE_PLAN: 'care.svg',
  X_RAY_DIET: 'lab.svg',
  CHANGE_STICKER: 'sticker.svg',
  NURSE_REVIEW_1: 'sticker.svg',
  NURSE_REVIEW_2: 'sticker.svg',
  PMR: 'sticker.svg',
  MEDS_CHECK: 'sticker.svg',
}

export const TODO_NAME = {
  CONSENT_OBTAINED: "CONSENT",
  FIRST_CHECK: "1st_eMAR/eTAR",
  SECOND_CHECK: "2nd_eMAR/eTAR",
  E_BOX_USED: "E_BOX_USED",
  DRUG_RECORD: "DRUG_RECORD",
  CARE_PLAN: "CARE_PLAN",
  X_RAY_DIET: "XRAY_DIET_LABREQ",
  CHANGE_STICKER: "CHANGE_STICKER",
  PMR: "PHYSICIAN_REVIEW",
  NURSE_REVIEW_1: "NURSE_PREP_1",
  NURSE_REVIEW_2: "NURSE_PREP_2",
  GENERAL: "GENERAL",
  VERBAL_ORDER: "VERBAL_ORDER",
  MEDS_CHECK: "MEDS_CHECK",
};

